name: 'LÖVE universal package'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package game
      run: |
        sudo apt-get install -q -y zip
        ./packaging/make-game.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: box-smasher.love
        path: packaging/bin/box-smasher.love

    - name: Upload to dev tag
      uses: pyTooling/Actions/releaser@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 'dev'
        files: packaging/bin/box-smasher.love
      if: github.event_name != 'pull_request'
